build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Keycloak"
  org.opencontainers.image.description: "Keycloak"
  org.opencontainers.image.source: "https://github.com/igor-panteleev/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
