name: "Keycloak"
description: "Keycloak"
version: "1.0.0"
slug: "keycloak"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/igor-panteleev/{arch}-hassio-keycloak"
url: "https://github.com/igor-panteleev/hassio-addons/tree/main/keycloak"
map:
  - share:rw
ports:
  8080/tcp: 9002
options:
  hostname: keyckoak.example.com
  hostname-admin: ka.example.com
  database:
    type: postgres
    username: keycloak
    password:
    url: "jdbc:postgresql://database/keycloak"
schema:
  hostname: str
  hostname-admin: str
  database:
    type: list(mariadb|mssql|mysql|postgres)
    username: str
    password: password
    url: str
