name: "Keycloak"
description: "Keycloak"
version: "1.0.3"
slug: "keycloak"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/igor-panteleev/{arch}-hassio-keycloak"
url: "https://github.com/igor-panteleev/hassio-addons/tree/main/keycloak"
map:
  - share:rw
ports:
  8080/tcp: 9002
options:
  hostname: keyckoak.example.com
  db_type: postgres
  db_username: keycloak
  db_password: homeassistant
  db_url: "jdbc:postgresql://database/keycloak"
schema:
  hostname: str
  db_type: list(mariadb|mssql|mysql|postgres)
  db_username: str
  db_password: password
  db_url: str
