name: "Keycloak"
description: "Keycloak"
version: "1.0.9"
slug: "keycloak"
arch:
  - aarch64
  - amd64
init: false
image: "ghcr.io/igor-panteleev/{arch}-hassio-keycloak"
url: "https://github.com/igor-panteleev/hassio-addons/tree/main/keycloak"
map:
  - share:rw
  - ssl
ports:
  8080/tcp: null
  8443/tcp: null
  9000/tcp: null
ports_description:
  8080/tcp: Web interface (http)
  8443/tcp: Web interface (https)
  9000/tcp: Management API
options:
  db_type: postgres
  db_username: keycloak
  db_password: homeassistant
  db_url: "jdbc:postgresql://database/keycloak"
  hostname_debug: false
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  db_type: list(mariadb|mssql|mysql|postgres)
  db_username: str
  db_password: password
  db_url: str
  hostname_debug: bool
  ssl: bool
  certfile: str
  keyfile: str
