name: "pgAdmin"
description: "This add-on is a pgAdmin."
version: "1.0.1"
slug: "pgAdmin"
arch:
  - aarch64
  - amd64
  - i386
init: false
image: "ghcr.io/igor-panteleev/{arch}-hassio-pgadmin"
url: "https://github.com/igor-panteleev/hassio-addons/tree/main/pgadmin"
ingress: true
ingress_stream: true
panel_icon: mdi:database-edit
