name: "pgAdmin"
description: "pgAdmin"
version: "1.0.4"
slug: "pgAdmin"
arch:
  - aarch64
  - amd64
  - i386
init: false
image: "ghcr.io/igor-panteleev/{arch}-hassio-pgadmin"
url: "https://github.com/igor-panteleev/hassio-addons/tree/main/pgadmin"
ingress: true
ingress_stream: true
panel_icon: mdi:database-edit
map:
  - share:rw
ports:
  9099/tcp: 9001
