build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21"
#  armhf: "ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.21"
#  armv7: "ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.21"
  i386: "ghcr.io/home-assistant/i386-base-python:3.13-alpine3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: pgAdmin"
  org.opencontainers.image.description: "This add-on allows you to run pgAdmin as Home Assistant addon."
  org.opencontainers.image.source: "https://github.com/igor-panteleev/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
