build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Samba AD DC"
  org.opencontainers.image.description: "Active Directory Domain Controller using Samba 4"
  org.opencontainers.image.source: "https://github.com/igor-panteleev/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
