build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Vouch Proxy"
  org.opencontainers.image.description: "Auth proxy that using Home Assistant as auth provider"
  org.opencontainers.image.source: "https://github.com/igor-panteleev/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
cosign:
  identity: https://github.com/igor-panteleev/hassio-addons/.*
  base_identity: https://github.com/home-assistant/docker-base/.*
